### ISSUE TITLE
Precompiling error on Julia 1.9.0 on Ubuntu 22.04

### ISSUE THREAD

**Issue by Cuda-Chen** [GenericMappingTools/GMT.jl#1190]
Hi community,

I have built GMT 6.4.0 from source (commit `c1a1c9`), and outside Julia `gmt` runs without any errors.
However, after I upgrade Julia to 1.9.0 on Ubuntu 22.04, GMT cannot be installed or import because of precompilation error.

FYI, this is my Julia environment:

```
julia> versioninfo()
Julia Version 1.9.0
Commit 8e630552924 (2023-05-07 11:25 UTC)
Platform Info:
  OS: Linux (x86_64-linux-gnu)
  CPU: 4 × Intel(R) Core(TM) i5-3230M CPU @ 2.60GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-14.0.6 (ORCJIT, ivybridge)
  Threads: 1 on 4 virtual cores
```

And this is the error messages of precompilation:

```julia
pkg> precompile
Precompiling project...
  ✗ GMT
  ✗ SeisPDF
  0 dependencies successfully precompiled in 217 seconds. 160 already precompiled.

ERROR: The following 2 direct dependencies failed to precompile:

SeisPDF [724aefe2-fcf9-4672-ae74-24b98027dbbf]

Failed to precompile SeisPDF [724aefe2-fcf9-4672-ae74-24b98027dbbf] to "/home/jio/.julia/compiled/v1.9/SeisPDF/jl_iDNMz3".
ERROR: LoadError: ArgumentError: cannot convert NULL to string
Stacktrace:
  [1] unsafe_string
    @ ./strings/string.jl:84 [inlined]
  [2] get_PS
    @ ~/.julia/packages/GMT/YoPcQ/src/gmt_main.jl:579 [inlined]
  [3] GMTJL_Get_Object(API::Ptr{Nothing}, X::GMT.GMT_RESOURCE)
    @ GMT ~/.julia/packages/GMT/YoPcQ/src/gmt_main.jl:732
  [4] gmt(::String, ::GMT.GMTdataset{Float64, 2}, ::Vararg{Any})
    @ GMT ~/.julia/packages/GMT/YoPcQ/src/gmt_main.jl:172
  [5] finish_PS_module(::Dict{Symbol, Any}, ::Vector{String}, ::String, ::Bool, ::Bool, ::Bool, ::GMT.GMTdataset{Float64, 2}, ::Vararg{Any})
    @ GMT ~/.julia/packages/GMT/YoPcQ/src/common_options.jl:4119
  [6] common_plot_xyz(::String, ::GMT.GMTdataset{Float64, 2}, ::String, ::Bool, ::Bool)
    @ GMT ~/.julia/packages/GMT/YoPcQ/src/psxy.jl:284
  [7] plot(arg1::Matrix{Float64}; first::Bool, kw::Base.Pairs{Symbol, Union{}, Tuple{}, NamedTuple{(), Tuple{}}})
    @ GMT ~/.julia/packages/GMT/YoPcQ/src/plot.jl:122
  [8] plot
    @ ~/.julia/packages/GMT/YoPcQ/src/plot.jl:101 [inlined]
  [9] macro expansion
    @ ~/.julia/packages/GMT/YoPcQ/src/GMT.jl:306 [inlined]
 [10] top-level scope
    @ ~/.julia/packages/PrecompileTools/EqjW2/src/workloads.jl:136
 [11] include
    @ ./Base.jl:457 [inlined]
 [12] include_package_for_output(pkg::Base.PkgId, input::String, depot_path::Vector{String}, dl_load_path::Vector{String}, load_path::Vector{String}, concrete_deps::Vector{Pair{Base.PkgId, UInt128}}, source::String)
    @ Base ./loading.jl:2010
 [13] top-level scope
    @ stdin:2
in expression starting at /home/jio/.julia/packages/GMT/YoPcQ/src/GMT.jl:1
in expression starting at stdin:2
ERROR: LoadError: Failed to precompile GMT [5752ebe1-31b9-557e-87aa-f909b540aa54] to "/home/jio/.julia/compiled/v1.9/GMT/jl_CdDIKp".
Stacktrace:
  [1] error(s::String)
    @ Base ./error.jl:35
  [2] compilecache(pkg::Base.PkgId, path::String, internal_stderr::IO, internal_stdout::IO, keep_loaded_modules::Bool)
    @ Base ./loading.jl:2260
  [3] compilecache
    @ ./loading.jl:2127 [inlined]
  [4] _require(pkg::Base.PkgId, env::String)
    @ Base ./loading.jl:1770
  [5] _require_prelocked(uuidkey::Base.PkgId, env::String)
    @ Base ./loading.jl:1625
  [6] macro expansion
    @ ./loading.jl:1613 [inlined]
  [7] macro expansion
    @ ./lock.jl:267 [inlined]
  [8] require(into::Module, mod::Symbol)
    @ Base ./loading.jl:1576
  [9] include(mod::Module, _path::String)
    @ Base ./Base.jl:457
 [10] include(x::String)
    @ SeisPDF ~/julia_code/SeisPDF.jl/src/SeisPDF.jl:1
 [11] top-level scope
    @ ~/julia_code/SeisPDF.jl/src/SeisPDF.jl:36
 [12] include
    @ ./Base.jl:457 [inlined]
 [13] include_package_for_output(pkg::Base.PkgId, input::String, depot_path::Vector{String}, dl_load_path::Vector{String}, load_path::Vector{String}, concrete_deps::Vector{Pair{Base.PkgId, UInt128}}, source::Nothing)
    @ Base ./loading.jl:2010
 [14] top-level scope
    @ stdin:2
in expression starting at /home/jio/julia_code/SeisPDF.jl/src/plot_pdf.jl:4
in expression starting at /home/jio/julia_code/SeisPDF.jl/src/SeisPDF.jl:1
in expression starting at stdin:2

GMT [5752ebe1-31b9-557e-87aa-f909b540aa54]

Failed to precompile GMT [5752ebe1-31b9-557e-87aa-f909b540aa54] to "/home/jio/.julia/compiled/v1.9/GMT/jl_UJYcP3".
ERROR: LoadError: ArgumentError: cannot convert NULL to string
Stacktrace:
  [1] unsafe_string
    @ ./strings/string.jl:84 [inlined]
  [2] get_PS
    @ ~/.julia/packages/GMT/YoPcQ/src/gmt_main.jl:579 [inlined]
  [3] GMTJL_Get_Object(API::Ptr{Nothing}, X::GMT.GMT_RESOURCE)
    @ GMT ~/.julia/packages/GMT/YoPcQ/src/gmt_main.jl:732
  [4] gmt(::String, ::GMT.GMTdataset{Float64, 2}, ::Vararg{Any})
    @ GMT ~/.julia/packages/GMT/YoPcQ/src/gmt_main.jl:172
  [5] finish_PS_module(::Dict{Symbol, Any}, ::Vector{String}, ::String, ::Bool, ::Bool, ::Bool, ::GMT.GMTdataset{Float64, 2}, ::Vararg{Any})
    @ GMT ~/.julia/packages/GMT/YoPcQ/src/common_options.jl:4119
  [6] common_plot_xyz(::String, ::GMT.GMTdataset{Float64, 2}, ::String, ::Bool, ::Bool)
    @ GMT ~/.julia/packages/GMT/YoPcQ/src/psxy.jl:284
  [7] plot(arg1::Matrix{Float64}; first::Bool, kw::Base.Pairs{Symbol, Union{}, Tuple{}, NamedTuple{(), Tuple{}}})
    @ GMT ~/.julia/packages/GMT/YoPcQ/src/plot.jl:122
  [8] plot
    @ ~/.julia/packages/GMT/YoPcQ/src/plot.jl:101 [inlined]
  [9] macro expansion
    @ ~/.julia/packages/GMT/YoPcQ/src/GMT.jl:306 [inlined]
 [10] top-level scope
    @ ~/.julia/packages/PrecompileTools/EqjW2/src/workloads.jl:136
 [11] include
    @ ./Base.jl:457 [inlined]
 [12] include_package_for_output(pkg::Base.PkgId, input::String, depot_path::Vector{String}, dl_load_path::Vector{String}, load_path::Vector{String}, concrete_deps::Vector{Pair{Base.PkgId, UInt128}}, source::Nothing)
    @ Base ./loading.jl:2010
 [13] top-level scope
    @ stdin:2
in expression starting at /home/jio/.julia/packages/GMT/YoPcQ/src/GMT.jl:1
in expression starting at stdin:2
```

I consider this may be a duplicated of #1052 .

Any help will be graceful, thanks!

**Comment by joa-quim** [comment]
Hi,

Honestly I don't understand these errors. Wow does SeisPDF.jl calls GMT.jl to trigger errors in latter? Anyway, mind you that GMT.jl now uses a GMT_jll artifact that is a newer version of the GMT binaries (than the one you have). Also note that GMT.jl is now version 1.1 but you have it restricted to ``GMT = "0.41"`` in you compat section of ``Project.toml``. So, first thing to try is to change that to ``GMT = "1"``.

If that doesn't work, I'll need to have more details on how GMT.jl is used in your package.

**Comment by joa-quim** [comment]
No, you do not have to care about the artifacts. That was just an information. Do you get any errors when doing
```
] up
```

**Comment by joa-quim** [comment]
And if I try adding from the url
```
(@v1.9) pkg> add https://github.com/Cuda-Chen/SeisPDF.jl/tree/main
     Cloning git-repo `https://github.com/Cuda-Chen/SeisPDF.jl`
    Updating git-repo `https://github.com/Cuda-Chen/SeisPDF.jl`
   Resolving package versions...
ERROR: Unsatisfiable requirements detected for package GMT [5752ebe1]:
 GMT [5752ebe1] log:
 ├─possible versions are: 1.1.0 or uninstalled
 ├─restricted to versions 0.41 by SeisPDF [724aefe2] — no versions left
 │ └─SeisPDF [724aefe2] log:
 │   ├─possible versions are: 0.0.1 or uninstalled
 │   └─SeisPDF [724aefe2] is fixed to version 0.0.1
 └─GMT [5752ebe1] is fixed to version 1.1.0
```
So the change in the compat is not active. You probably need to register a new version of SeisPDF where the compat change is visible externally.

**Comment by Cuda-Chen** [comment]
Hi @joa-quim ,

Thanks for your tips!
Yet this may take for a while, and I will update my findings once I register the new version of SeisPDF.

**Comment by Cuda-Chen** [comment]
> Let's try to keep the SeisPDF and GMT building errors separately. Does this error too?
> 
> ```
> import Pkg; Pkg.build("GMT")
> ```
> 

Yes, this will emit an error about `LoadError: ArgumentError: cannot convert NULL to string`.

**Comment by joa-quim** [comment]
But that is using the older GMT.jl v0.44 (though still I don't know why it errors that way). You need to be able to update your GMT.jl to the 1.xxx series and for that you probably need to update the registered version of SeisPDF (registering a new version, when all goes well, its a ~15 min job)

**Comment by Cuda-Chen** [comment]
Hi @joa-quim ,

I try to add `GMT` in a fresh Julia project and I still receive precompile errors about `LoadError: ArgumentError: cannot convert NULL to string`.
I guess there are some problems for my system.
I decide to re-compile then install my GMT then try to add GMT.jl again.

**Comment by Cuda-Chen** [comment]
Hi @joa-quim ,

I consider I have found the solution.
Here are the steps to resolve this issue:
1. Clone GMT with latest commit.
2. Build-then-install GMT from source.
3. Run `] rm GMT` in your Julia project.
4. Run `] add GMT` in your Julia project.
5. Run `] precompile`.
6. Import GMT.jl (`using GMT`) to check whether we encounter any errors or not.

I think we may add some advice about re-build-then-install notice if users install their GMT by tarball.

Anyway, thanks for your help!

**Comment by joa-quim** [comment]
First, the important is that you solved the problem, but you'll get surprised (I think). If do, and see
```
julia> GMT.have_jll
1

julia> GMT.devdate
"0001.01.01"
```
I'm not so sure about the last one that in fact should show the GMT compiling date. But the first one is saying that what is being used is the GMT_jll artifact and not the local GMT installation. See [here ](https://github.com/GenericMappingTools/GMT.jl#install) for general instructions for when we want to force the use of a GMT own build (they worked when I implemented this functionality but haven't tried in a while and those things break so easily...)

Still don't understand what happened but likely the remove and reinstall of GMT.jll was what fix it.

**Comment by Cuda-Chen** [comment]
> See [here ](https://github.com/GenericMappingTools/GMT.jl#install)for general instructions for when we want to force the use of a GMT own build
> 

Yes, I also find these instructions. Maybe I should use these instructions if I want to use system-wide GMT.

**Comment by joa-quim** [comment]
One normally should not need to worry about that. Only if some new feature or bug fix is not yet in the GMT_jll artifact.
Mind you also that if you are using an Ubuntu family linux the risk of linking against an old GDAL version is quite high and there are things that might not work in GMT.jl

**Comment by joa-quim** [comment]
All solved? Can we close this?

Another thing, it would be nice if you have a cool/simple example of a SeisPDF plot that you could show in the [GMT forum](https://forum.generic-mapping-tools.org/c/Show-your-nice-example-script/10)

**Comment by Cuda-Chen** [comment]
Hi @joa-quim ,
All solved, thanks for the reminder, and I will close this issue by myself.

> Another thing, it would be nice if you have a cool/simple example of a SeisPDF plot that you could show in the [GMT forum](https://forum.generic-mapping-tools.org/c/Show-your-nice-example-script/10)

Thanks! I will show my example of a SeisPDF plot which plots a PDF for a given trace.
